---
- name: Setting distribution fact for non Debian based distribution
  set_fact:
    distribution: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}"
  when: ansible_os_family != 'Debian'

- name: Setting distribution fact for Debian based distribution
  set_fact:
    distribution: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}"
  when: ansible_os_family == 'Debian'

- name: Include variable file for {{ distribution }}
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ distribution }}.yml"

## Update packages
- name: Unhold system packages with apt for {{ distribution }}
  shell: apt-mark unhold "{{ unholdExtraPackages }}"
  args:
    executable: /bin/bash
  when:
    ansible_os_family == 'Debian' 
    and 
    updateSystemPackages is defined 
    and 
    unholdExtraPackages is defined
    and
    unholdExtraPackages|length > 0

- name: Update all system packages to their latest version with apt for {{ distribution }}
  apt:
    name: "*"
    update_cache: yes
    state: latest
  when: 
    ansible_os_family == 'Debian' 
    and 
    updateSystemPackages is defined 
    and 
    updateSystemPackages == "all"

- name: Update {{ updateSystemPackages }} system packages to their latest version with apt for {{ distribution }}
  apt:
    name: "{{ updateSystemPackages }}"
    update_cache: yes
    state: latest
  when: 
    ansible_os_family == 'Debian' 
    and 
    updateSystemPackages is defined 
    and 
    updateSystemPackages != "all"

## Install and manage packages
- name: Install base packages with apt for {{ distribution }}
  apt: 
    name: "{{ basePackages }}"
    update_cache: true
    state: present
  when: ansible_os_family == 'Debian' and basePackages is defined

- name: Install extra packages with apt for {{ distribution }}
  apt: 
    name: "{{ installExtraPackages }}"
    update_cache: true
    state: present
  when: ansible_os_family == 'Debian' and installExtraPackages is defined

- name: Remove extra packages with apt for {{ distribution }}
  apt: 
    name: "{{ removeExtraPackages }}"
    update_cache: true
    state: absent
  when: ansible_os_family == 'Debian' and removeExtraPackages is defined

- name: Hold extra packages with dpkg for {{ distribution }}
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - "{{ holdExtraPackages }}"
  when: ansible_os_family == 'Debian' and holdExtraPackages is defined
